const { DataTypes, Model } = require('sequelize');

class FemalePlayers extends Model { }

const femalePlayers = (sequelize) => {
    return FemalePlayers.init({
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        fifa_version: DataTypes.STRING,
        fifa_update: DataTypes.STRING,
        player_face_url: DataTypes.STRING,
        long_name: DataTypes.STRING,
        player_positions: DataTypes.STRING,
        club_name: DataTypes.STRING,
        nationality_name: DataTypes.STRING,
        overall: DataTypes.INTEGER,
        potential: DataTypes.INTEGER,
        value_eur: DataTypes.INTEGER,
        wage_eur: DataTypes.INTEGER,
        age: DataTypes.INTEGER,
        height_cm: DataTypes.INTEGER,
        weight_kg: DataTypes.INTEGER,
        preferred_foot: DataTypes.STRING,
        weak_foot: DataTypes.INTEGER,
        skill_moves: DataTypes.INTEGER,
        international_reputation: DataTypes.INTEGER,
        work_rate: DataTypes.STRING,
        body_type: DataTypes.STRING,
        pace: DataTypes.INTEGER,
        shooting: DataTypes.INTEGER,
        passing: DataTypes.INTEGER,
        dribbling: DataTypes.INTEGER,
        defending: DataTypes.INTEGER,
        physic: DataTypes.INTEGER,
        attacking_crossing: DataTypes.INTEGER,
        attacking_finishing: DataTypes.INTEGER,
        attacking_heading_accuracy: DataTypes.INTEGER,
        attacking_short_passing: DataTypes.INTEGER,
        attacking_volleys: DataTypes.INTEGER,
        skill_dribbling: DataTypes.INTEGER,
        skill_curve: DataTypes.INTEGER,
        skill_fk_accuracy: DataTypes.INTEGER,
        skill_long_passing: DataTypes.INTEGER,
        skill_ball_control: DataTypes.INTEGER,
        movement_acceleration: DataTypes.INTEGER,
        movement_sprint_speed: DataTypes.INTEGER,
        movement_agility: DataTypes.INTEGER,
        movement_reactions: DataTypes.INTEGER,
        movement_balance: DataTypes.INTEGER,
        power_shot_power: DataTypes.INTEGER,
        power_jumping: DataTypes.INTEGER,
        power_stamina: DataTypes.INTEGER,
        power_strength: DataTypes.INTEGER,
        power_long_shots: DataTypes.INTEGER,
        mentality_aggression: DataTypes.INTEGER,
        mentality_interceptions: DataTypes.INTEGER,
        mentality_positioning: DataTypes.INTEGER,
        mentality_vision: DataTypes.INTEGER,
        mentality_penalties: DataTypes.INTEGER,
        mentality_composure: DataTypes.INTEGER,
        defending_marking: DataTypes.INTEGER,
        defending_standing_tackle: DataTypes.INTEGER,
        defending_sliding_tackle: DataTypes.INTEGER,
        goalkeeping_diving: DataTypes.INTEGER,
        goalkeeping_handling: DataTypes.INTEGER,
        goalkeeping_kicking: DataTypes.INTEGER,
        goalkeeping_positioning: DataTypes.INTEGER,
        goalkeeping_reflexes: DataTypes.INTEGER,
        goalkeeping_speed: DataTypes.INTEGER,
        player_traits: DataTypes.STRING,
    }, {
        sequelize,
        modelName: 'FemalePlayers',
        tableName: 'players',
        timestamps: false
    })
}

module.exports = femalePlayers;
